// angular-blog/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { Global } from '../../services/global';
import swal from 'sweetalert';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article: Article;
  public url: string;

  constructor(
    private _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe(params => {
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        response => {
          //console.log(response);
          if (response.article) {
            this.article = response.article;
          } else {
            //no existe
            this._router.navigate(['/home']);
          }
        },
        error => {
          //console.log(error);
          this._router.navigate(['/home']);
        }

      );
    });
  }

  delete(id) {
    swal({
      title: "Seguro?",
      text: "Una vez borrado el artículo, será imposible recuperarlo",
      icon: "warning",
      buttons: [true, true],
      dangerMode: true
    })
      .then((willDelete) => {
        if (willDelete) {
          this._articleService.delete(id).subscribe(
            response => {
              swal("El artículo ha sido borrado", {
                icon: "success",
              });
              this._router.navigate(['/blog']);
            },
            error => {
              console.log(error);
              this._router.navigate(['/blog']);
            }
          );
        } else {
          swal("Calma, nada ha sido borrado");
        }
      });
  }

}

<div class="center">

    <section id="content">

        <article class="article-item article-detail" *ngIf="article">
            <div class="image-wrap">
                <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image">
                <img src="assets/images/no_image.jpg" alt="{{article.title}}" *ngIf="!article.image">
            </div>
            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">
                {{article.date | amLocale: 'en' | amDateFormat:'LL'}}
            </span>
            <p>
                {{article.content}}
            </p>

            <div class="buttons">
                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>    
            </div>
            
            <div class="clearfix"></div>
        </article>

    </section>

    <app-sidebar></app-sidebar>

</div>

// react-app-blog/src/components/Article.js
import React, { Component } from 'react';
import axios from 'axios';
import Global from '../Global';
import Sidebar from './Sidebar';
import Moment from 'react-moment';
import 'moment/locale/es';
import { Redirect, Link } from 'react-router-dom';
import swal from 'sweetalert';

class Article extends Component {

    url = Global.url;

    state = {
        article: false,
        status: null
    };

    componentWillMount() {
        this.getArticle();
    }

    getArticle = () => {
        var id = this.props.match.params.id;

        axios.get(this.url + 'article/' + id)
            .then(res => {
                this.setState({
                    article: res.data.article,
                    status: 'success'
                });
            }).catch(err => {
                this.setState({
                    articles: false,
                    status: 'success'
                });
            });
    }

    deleteArticle = (id) => {

        swal({
            title: "Seguro de eliminarlo?",
            text: "Una vez eliminado, este no será posible recuperarlo!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    axios.delete(this.url + 'article/' + id)
                        .then(res => {
                            this.setState({
                                articles: res.data.article,
                                status: 'deleted'
                            });

                            swal(
                                'Articulo eliminado',
                                'El articulo ha sido eliminado correctamente',
                                'success'
                            );
                        });
                } else {
                    swal(
                        "No te preocupes!", 
                        'Nada ha sido eliminado'
                    );
                }
            });
    }

    render() {
        if (this.state.status === 'deleted') {
            return <Redirect to="/blog"></Redirect>;
        }
        var article = this.state.article;
        return (
            <div className="center">
                <section id="content">
                    {article &&
                        <article className="article-item article-detail">
                            <div className="image-wrap">
                                {article.image !== null ? (
                                    <img src={this.url + 'get-image/' + article.image} alt={article.title} />
                                ) :
                                    (
                                        <img src="https://www.retirementlivingsourcebook.com/images/NoImageAvailable.png" alt="" />
                                    )
                                }
                            </div>
                            <h1 className="subheader">{article.title}</h1>
                            <span className="date">
                                <Moment locale="es" fromNow>{article.date}</Moment>
                            </span>
                            <p>
                                {article.content}
                            </p>

                            <button onClick={
                                () => {
                                    this.deleteArticle(article._id)
                                }
                            } className="btn btn-danger">Eliminar</button>

                            <Link to={"/blog/editar/" + article._id} className="btn btn-warning">Editar</Link>

                            <div class="clearfix"></div>
                        </article>
                    }
                    {!article && this.state.status === 'success' &&
                        <div id="article">
                            <h2 className="subheader">El artículo no existe</h2>
                            <p>
                                Intentalo más tarde.
                            </p>
                        </div>
                    }
                    {this.state.status == null &&
                        <div id="article">
                            <h2 className="subheader">Cargando...</h2>
                            <p>
                                Espera un momento.
                            </p>
                        </div>
                    }
                </section>
                <Sidebar></Sidebar>
            </div>
        );
    }
}

export default Article;
