// angular-blog/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import {Route, ActivatedRoute, Params, Router} from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public searchString: string;

  constructor(
    private _router: Router, 
    private _route: ActivatedRoute
  ) { }

  ngOnInit(): void {
  }

  goSearch(){
    //Realizar busqueda utilizando el OnSubmit
    //redireccion
    //alert(this.searchString);
    this._router.navigate(['/buscar', this.searchString]);
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Publica algo</h3>
        <a [routerLink]="['/blog/crear']" class="btn btn-success">Crear publicación</a>
    </div>
    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra algo</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" [(ngModel)]="searchString"/>
            <input type="submit" name="submit" value="Buscar" class="btn">
        </form>
    </div>
</aside>
<div class="clearfix"></div>

// react-app-blog/src/components/Sidebar.js
import React, { Component } from 'react';
import {Redirect, Link} from 'react-router-dom'; 

class Sidebar extends Component {

    searchRef = React.createRef();

    state = {
        search: "",
        redirect: false
    };
    
    redirectToSearch = (e) => {
        e.preventDefault();
        this.setState({
            search: this.searchRef.current.value,
            redirect: true
        });
    }

    render() {

        if(this.state.redirect){
            return(
                <Redirect
                    to={'/redirect/'+this.state.search}
                >
                </Redirect>
            );
        }


        return (
            //JSX
            <aside id="sidebar">
                {this.props.blog === "true" &&
                    <div id="nav-blog" className="sidebar-item">
                        <h3>Publica algo</h3>
                        <Link to={'/blog/crear'} className="btn btn-success">Crear publicación</Link>
                    </div>
                }
                <div id="search" className="sidebar-item">
                    <h3>Buscador</h3>
                    <p>Encuentra algo</p>
                    <form onSubmit={this.redirectToSearch}>
                        <input type="text" name="search" ref={this.searchRef} />
                        <input type="submit" name="submit" value="Buscar" className="btn" />
                    </form>
                </div>
            </aside>
        );
    }
}

export default Sidebar;
