// react-app-blog/src/components/Formulario.js
import React, { Component } from 'react';
import Sidebar from './Sidebar';

class Formulario extends Component {

    nombreRef = React.createRef();
    apellidoRef = React.createRef();
    bioRef = React.createRef();
    generoHRef = React.createRef();
    generoMRef = React.createRef();
    generoORef = React.createRef();

    /**
     * 
     * @param {state} 
     */

     state = {
         //objeto vacio para rellenarlo
         user: {}
     }

    recibirFormulario = (e) => {
        e.preventDefault();

        var genero = 'hombre';

        if(this.generoHRef.current.checked){
            genero = this.generoHRef.current.value;
        }else if(this.generoMRef.current.checked){
            genero = this.generoMRef.current.value;
        }else{
            genero = this.generoORef.current.value;
        }

        var user = {
            nombre: this.nombreRef.current.value,
            apellidos: this.apellidoRef.current.value,
            bio: this.bioRef.current.value,
            genero: genero
        }

        this.setState({
            user: user
        });

        console.log('Formulario enviado');
        console.log(user);
    }

    render() {

        if(this.state.user.nombre){
            var user = this.state.user;
        }

        return (

            <div id="formulario">
                <div className="center">
                    <div id="content">
                        {/*Creacion de un formulario*/}
                        <h1 class="subheader">Formulario</h1>

                        {/*Mostrar datos del formulario*/}
                        {this.state.user.nombre &&
                            <div id="user-data">
                                <p>Nombre: <strong>{user.nombre}</strong></p>
                                <p>Apellidos: <strong>{user.apellidos}</strong></p>
                                <p>Biografía: <strong>{user.bio}</strong></p>
                                <p>Género: <strong>{user.genero}</strong></p>
                            </div>
                        }

                        {/*OnChange - Muestra los datos del formulario de una manera reactiva
                        desde la pantalla donde tenemos anidado el div que muestra los datos */}

                        <form className="mid-form" onSubmit={this.recibirFormulario} onChange={this.recibirFormulario}>
                            <div className="form-group">
                                <label htmlFor="nombre">Nombre</label>
                                <input type="text" name="nombre" ref={this.nombreRef}/>
                            </div>
                            <div className="form-group">
                                <label htmlFor="apellido">Apellido</label>
                                <input type="text" name="apellido" ref={this.apellidoRef} />
                            </div>
                            <div className="form-group">
                                <label htmlFor="bio">Biografía</label>
                                <textarea name="bio" id="" cols="30" rows="10" ref={this.bioRef}></textarea>
                            </div>
                            <div className="form-group radioButtons">
                                <input type="radio" name="genero" id="" value="hombre" ref={this.generoHRef}/>Hombre
                                 <input type="radio" name="genero" id="" value="mujer" ref={this.generoMRef}/>Mujer
                                <input type="radio" name="genero" id="" value="otro" ref={this.generoORef}/>Otro
                            </div>
                            <div className="clearfix"></div>
                            <input type="submit" value="Enviar" className="btn btn-success"/>
                        </form>
                    </div>
                        <Sidebar
                            blog="false"
                        ></Sidebar>
                    </div>
                </div>
        );
    }
}

export default Formulario;

// angular-blog/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo: string;

  constructor() { 
    this.user = {
      nombre: '',
      apellido: '',
      bio: '',
      genero: ''
    };
   }

  ngOnInit(): void {
  }

  onSubmit(){
    alert('formulario enviado');
    console.log(this.user);
  }

  /**
   * Evento click
   */
  hasDadoClick(){
    alert('Has dado click');
  }
  /**
   * Evento blur
   */
  hasSalido(){
    alert('Has dado ENTER');
  }



}

<app-slider [nombre]="'Formulario'" [size]="'small'">
</app-slider>

<div class="center">

    <section id="content">

        <h1 class="subheader">Formulario</h1>

        <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" 
                    required pattern="[a-zA-Z]+"/>
                <!--validacion-->
                <small *ngIf="!nombre.valid && nombre.touched">
                    El nombre no es valido
                </small>
            </div>
            <div class="form-group">
                <label for="apellido">Apellido</label>
                <input type="text" name="apellido" #apellido="ngModel" [(ngModel)]="user.apellido" required/>
                <!--validacion-->
                <small *ngIf="!apellido.valid && apellido.touched">
                    El apellido no es valido
                </small>
            </div>
            <div class="form-group">
                <label for="bio">Biografía</label>
                <textarea name="bio"  #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
                <!--validacion-->
                <small *ngIf="!bio.valid && bio.touched">
                    La biografía no es valida
                </small>
            </div>
            <div class="form-group radioButtons">
                <input type="radio" name="genero" id="" value="hombre" #genero="ngModel" [(ngModel)]="user.genero" required/>Hombre
                <input type="radio" name="genero" id="" value="mujer" #genero="ngModel" [(ngModel)]="user.genero" />Mujer
                <input type="radio" name="genero" id="" value="otro" #genero="ngModel" [(ngModel)]="user.genero" />Otro
                <!--validacion-->
                <small *ngIf="!genero.valid && genero.touched">
                    El genero no es valido
                </small>
            </div>
            <div class="clearfix"></div>
            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid">

        </form>

        <h2 class="subheader">
            Eventos
        </h2>
        <!--Evento de click sobre los botones-->
        <button (click)="hasDadoClick()">Click-me</button>
        <!--
            Blur{
                refleja cuando has salido de un campo al dar click
            }
            keyup{
                alerta de cuando una tecla ha sido levantada
            }
        -->
        <input type="text" [(ngModel)]="campo"  (keyup.enter)="hasSalido()"/>
        {{campo}}
    </section>

    <br>

    <app-sidebar></app-sidebar>

</div>
